- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
      exclude: Guidelines.md
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
